/*
Deployment script for StaffDB

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "StaffDB"
:setvar DefaultFilePrefix "StaffDB"
:setvar DefaultDataPath "C:\Users\mahe\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB\"
:setvar DefaultLogPath "C:\Users\mahe\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Creating [dbo].[Administrator]...';


GO
CREATE TABLE [dbo].[Administrator] (
    [id]       VARCHAR (50) NOT NULL,
    [email]    VARCHAR (50) NOT NULL,
    [password] VARCHAR (50) NOT NULL,
    PRIMARY KEY CLUSTERED ([id] ASC)
);


GO
PRINT N'Creating [dbo].[Request]...';


GO
CREATE TABLE [dbo].[Request] (
    [Id]  INT IDENTITY (1, 1) NOT NULL,
    [Tid] INT NOT NULL,
    [Sid] INT NOT NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [unique_request] UNIQUE NONCLUSTERED ([Tid] ASC, [Sid] ASC)
);


GO
PRINT N'Creating [dbo].[Student]...';


GO
CREATE TABLE [dbo].[Student] (
    [Sid]    INT          IDENTITY (1, 1) NOT NULL,
    [Sname]  VARCHAR (50) NOT NULL,
    [Smail]  VARCHAR (50) NOT NULL,
    [Simage] IMAGE        NULL,
    [Sdob]   DATE         NOT NULL,
    [Tid]    INT          NULL,
    PRIMARY KEY CLUSTERED ([Sid] ASC)
);


GO
PRINT N'Creating [dbo].[Teacher]...';


GO
CREATE TABLE [dbo].[Teacher] (
    [Tid]       INT          NOT NULL,
    [Tfname]    VARCHAR (50) NOT NULL,
    [Tlname]    VARCHAR (50) NOT NULL,
    [Tmail]     VARCHAR (50) NOT NULL,
    [Tpassword] VARCHAR (50) NOT NULL,
    PRIMARY KEY CLUSTERED ([Tid] ASC)
);


GO
PRINT N'Update complete.';


GO
